### ISSUE TITLE
networking: find all subnets by category

### ISSUE THREAD

**Issue by NewestUser** [clouway-incubator/subnet-management-system#17]
There should be the possibility to retrieve all subnets that are associated with a given category. 
- can be accessed via service

**Comment by mgenov** [comment]
Why you are separating the issue?

**Comment by mgenov** [comment]
i.e backend and frontend ?

**Comment by mgenov** [comment]
How will I get value when I separate them that way ?

**Comment by NewestUser** [comment]
I agree that just finding subnets or bindings gives no value.

But all this functionality is needed when a tree view of the network is displayed.
Currently if there is a issue for just displaying network tree it will include to much functionality.

I will remove the labels assigned to such issues.

I am open for suggestions.
